name: op_result
description: A generic result type for handling success and error cases in a type-safe manner.
version: 0.1.0
repository: https://github.com/cantini-dev/dc-dart-op_result

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
