name: op_result
description: A generic result type for handling success and error cases in a type-safe manner.
version: 0.2.2
repository: https://github.com/cantini-dev/dc-dart-op_result
license: BSD-3-Clause

environment:
  sdk: ^3.7.0

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
